[package]
name = "spooky"
version = "0.1.0"
authors = ["Juraj Michálek <juraj.michalek@gmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
esp32s2-hal = { package = "esp32s2-hal", git = "https://github.com/esp-rs/esp-hal.git" }

esp-backtrace = { git = "https://github.com/esp-rs/esp-backtrace", features = [
    "esp32s2",
    "panic-handler",
    "print-uart",
] }
xtensa-atomic-emulation-trap = "0.1.0"
xtensa-lx-rt = { version = "0.12.0", features = ["esp32s2"], optional = true }
esp-println = { version = "0.2.1", features = [ "esp32s2" ] }
embedded-graphics = "0.7"
embedded-hal = "0.2"
display-interface = "0.4"
display-interface-spi = "0.4"
ili9341 = { version = "0.5", git = "https://github.com/yuri91/ili9341-rs" }
st7789 = "0.6"
panic-halt = "0.2"

[features]
default = ["rt", "esp32s2_usb_otg"]
rt = ["xtensa-lx-rt"]

# Enable this feature in case you have an ESP32S2-USB-OTG preview board
esp32s2_usb_otg = []
